export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL";
export const CREATE_BLOG_RESET = "CREATE_BLOG_RESET";

export const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST";
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL";
export const UPDATE_BLOG_RESET = "UPDATE_BLOG_RESET";

export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL";
export const DELETE_BLOG_RESET = "DELETE_BLOG_RESET";

export const ALL_BLOG_LOADING = "ALL_BLOG_LOADING";
export const ALL_BLOG_SUCCESS = "ALL_BLOG_SUCCESS";
export const ALL_BLOG_FAIL = "ALL_BLOG_FAIL";
export const ALL_BLOG_RESET = "ALL_BLOG_RESET";

export const GET_BLOGS_CATEGORY_ID_LOADING = "GET_BLOGS_CATEGORY_ID_LOADING";
export const GET_BLOGS_CATEGORY_ID_SUCCESS = "GET_BLOGS_CATEGORY_ID_SUCCESS";
export const GET_BLOGS_CATEGORY_ID_FAIL = "GET_BLOGS_CATEGORY_ID_FAIL";

export const GET_BLOGS_BY_USER_LOADING = "GET_BLOGS_BY_USER_LOADING";
export const GET_BLOGS_BY_USER_SUCCESS = "GET_BLOGS_BY_USER_SUCCESS";
export const GET_BLOGS_BY_USER_FAIL = "GET_BLOGS_BY_USER_FAIL";
