export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";
export const CREATE_COMMENT_RESET = "CREATE_COMMENT_RESET";

export const UPDATE_COMMENT_REQUEST = "UPDATE_COMMENT_REQUEST";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAIL = "UPDATE_COMMENT_FAIL";
export const UPDATE_COMMENT_RESET = "UPDATE_COMMENT_RESET";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";
export const DELETE_COMMENT_RESET = "DELETE_COMMENT_RESET";

export const ALL_COMMENT_LOADING = "ALL_COMMENT_LOADING";
export const ALL_COMMENT_SUCCESS = "ALL_COMMENT_SUCCESS";
export const ALL_COMMENT_FAIL = "ALL_COMMENT_FAIL";
export const ALL_COMMENT_RESET = "ALL_COMMENT_RESET";

export const GET_BLOGS_CATEGORY_ID_LOADING = "GET_BLOGS_CATEGORY_ID_LOADING";
export const GET_BLOGS_CATEGORY_ID_SUCCESS = "GET_BLOGS_CATEGORY_ID_SUCCESS";
export const GET_BLOGS_CATEGORY_ID_FAIL = "GET_BLOGS_CATEGORY_ID_FAIL";

export const GET_BLOGS_BY_USER_LOADING = "GET_BLOGS_BY_USER_LOADING";
export const GET_BLOGS_BY_USER_SUCCESS = "GET_BLOGS_BY_USER_SUCCESS";
export const GET_BLOGS_BY_USER_FAIL = "GET_BLOGS_BY_USER_FAIL";
